feat(#1pjar54): creating type class and tests.
Artur-Arantes/offnance pull request #14
Opened 2021-10-29 12:34 UTC by Artur-Arantes

-type.class
-typedto.class
-typeRepository.class
-type-integration-tests
-type-unit-tests

Signed-off-by: Artur Arantes T <artur.a.tiraboschi@gmail.com>

2021-10-31 12:12 UTC, JamalXVI requested changes

2021-10-31 12:12 UTC, JamalXVI commented on src/main/java/br/com/artur/offnance/domain/User.java
> +@Setter
Precisa do Setter em todos mesmo?

2021-10-31 12:12 UTC, JamalXVI commented on src/main/java/br/com/artur/offnance/service/imp/TypeServiceImp.java
> +  public TypeOutputDto create(TypeDto dto) {
Aqui precisa do final e @NonNull, por ser entrada pública
```
  public TypeOutputDto create(final @NonNull TypeDto dto) {
```

2021-10-31 12:12 UTC, JamalXVI commented on src/test/java/br/com/artur/offnance/controller/TypeControllerIntegrationTest.java
> +          .name("Anything").idUser(1l).build();
`1L` maiusculo pfv

2021-10-31 12:12 UTC, JamalXVI commented on src/test/java/br/com/artur/offnance/controller/TypeControllerIntegrationTest.java
> +      assertThat(tipo.getName()).isNotEqualTo(typeDto.getName());
Este teste está confuso, o que é para ele fazer? Consegue explicar? E ainda faltam testes: Para o caso do usuário não ser entrado é um exemplo

2021-10-31 12:12 UTC, JamalXVI commented on src/test/java/br/com/artur/offnance/service/imp/TypeServiceTest.java
> +    }
Este teste aqui objetivamente não testa nada

2021-10-31 20:53 UTC, Artur-Arantes commented on src/main/java/br/com/artur/offnance/service/imp/TypeServiceImp.java
> +  public TypeOutputDto create(TypeDto dto) {
resolvido

2021-10-31 20:53 UTC, Artur-Arantes commented on src/test/java/br/com/artur/offnance/controller/TypeControllerIntegrationTest.java
> +          .name("Anything").idUser(1l).build();
resolvido

2021-10-31 21:34 UTC, Artur-Arantes commented on src/test/java/br/com/artur/offnance/controller/TypeControllerIntegrationTest.java
> +      assertThat(tipo.getName()).isNotEqualTo(typeDto.getName());
acho que arrumei

2021-10-31 21:47 UTC, Artur-Arantes commented on src/test/java/br/com/artur/offnance/service/imp/TypeServiceTest.java
> +    }
apaguei ele

2021-11-01 14:41 UTC, JamalXVI approved these changes

2021-11-01 14:51 UTC, merged