feat(#1qerqp2): create data
Artur-Arantes/offnance pull request #18
Opened 2021-11-04 17:18 UTC by Artur-Arantes

Signed-off-by: Artur Arantes T <artur.a.tiraboschi@gmail.com>

2021-11-08 11:39 UTC, JamalXVI requested changes

2021-11-08 11:39 UTC, JamalXVI commented on src/main/java/br/com/artur/offnance/config/ControllerAdviceRest.java
> +  }
?????????

2021-11-08 11:39 UTC, JamalXVI commented on src/main/java/br/com/artur/offnance/domain/User.java
> +@OneToMany(mappedBy = "user", targetEntity = Tag.class, fetch = FetchType.LAZY)
Falta alinhar esta classe

2021-11-08 11:39 UTC, JamalXVI commented on src/main/java/br/com/artur/offnance/config/ControllerAdviceRest.java
> +  }
Aqui seria TypeNotFoundException

2021-11-09 17:36 UTC, Artur-Arantes commented on src/main/java/br/com/artur/offnance/domain/User.java
> +@OneToMany(mappedBy = "user", targetEntity = Tag.class, fetch = FetchType.LAZY)
feito

2021-11-09 17:37 UTC, Artur-Arantes commented on src/main/java/br/com/artur/offnance/config/ControllerAdviceRest.java
> +  }
como assim henrique? a gente ja tem um pro type

2021-11-09 19:16 UTC, merged